# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-26 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JmeterSvrModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='测试计划名称')),
                ('hostIP', models.GenericIPAddressField(verbose_name='Jmeter主机IP')),
                ('agentIP', jsonfield.fields.JSONField(default='{}', help_text='暂且为空', verbose_name='执行机IP')),
                ('username', models.CharField(max_length=64, verbose_name='测试计划名称')),
                ('remotePath', models.CharField(max_length=64, verbose_name='Jmeter安装路径')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
