# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-16 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8001/'),
        ),
    ]
