# Generated by Django 2.0.3 on 2018-03-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_enable', models.BooleanField(default=True)),
                ('url_path', models.URLField()),
                ('url_param', models.TextField()),
                ('real_Result', models.TextField()),
                ('expected_result', models.TextField()),
                ('description', models.CharField(max_length=256)),
                ('on_going', models.BooleanField(default=True)),
                ('test_suit', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.TestSuit')),
            ],
        ),
    ]
