# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-16 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testproject',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='testproject',
            name='highlighted',
        ),
        migrations.AddField(
            model_name='testcase',
            name='url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='testproject',
            name='owner',
            field=models.CharField(max_length=64),
        ),
    ]
