# Generated by Django 2.0.3 on 2018-03-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='pass_or_fail',
            field=models.BooleanField(default=None),
        ),
    ]
