# Generated by Django 2.0.3 on 2018-03-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_testcase_pass_or_fail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='url_path',
            field=models.CharField(max_length=64),
        ),
    ]
